# Generated by Django 5.2.3 on 2025-07-27 17:28

import cloudinary.models
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_newsletteremail_returnrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
